/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reto5Equipo10G1M3.Reto5;

import java.util.Optional;

/**
 *
 * @author JessidEscobar
 */
public class VentanaPeliculas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPeliculas
     */
    peliculaRepositorio repo;

    public VentanaPeliculas() {
        initComponents();
        String[] args = {};
        this.setLocationRelativeTo(null);
        Reto5Application.ServerSpring(args);
        repo = SpringContext.getBean(peliculaRepositorio.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        peliculaResumen = new javax.swing.JTextArea();
        lbNotificaciones = new javax.swing.JLabel();
        btnCrearPeli = new javax.swing.JButton();
        btnEliminarpeli = new javax.swing.JButton();
        btnConsultarPeli = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        peliculaTitulo = new javax.swing.JTextField();
        peliculaDirector = new javax.swing.JTextField();
        pelliculaAn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        peliculaId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setToolTipText("");

        jButton2.setText("LIMPIAR DATOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setToolTipText("");

        peliculaResumen.setColumns(20);
        peliculaResumen.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        peliculaResumen.setLineWrap(true);
        peliculaResumen.setRows(5);
        peliculaResumen.setWrapStyleWord(true);
        jScrollPane1.setViewportView(peliculaResumen);

        lbNotificaciones.setForeground(new java.awt.Color(255, 255, 255));
        lbNotificaciones.setText("Bienvenido a su administrador de confianza RedFlix33");

        btnCrearPeli.setBackground(new java.awt.Color(0, 102, 0));
        btnCrearPeli.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnCrearPeli.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearPeli.setText("CREAR PELÍCULA");
        btnCrearPeli.setToolTipText("");
        btnCrearPeli.setBorder(null);
        btnCrearPeli.setMargin(new java.awt.Insets(8, 14, 8, 14));
        btnCrearPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPeliActionPerformed(evt);
            }
        });

        btnEliminarpeli.setBackground(new java.awt.Color(204, 51, 0));
        btnEliminarpeli.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnEliminarpeli.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarpeli.setText("ELIMINAR PELÍCULA");
        btnEliminarpeli.setToolTipText("");
        btnEliminarpeli.setBorder(null);
        btnEliminarpeli.setMargin(new java.awt.Insets(8, 14, 8, 14));
        btnEliminarpeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarpeliActionPerformed(evt);
            }
        });

        btnConsultarPeli.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnConsultarPeli.setText("CONSULTAR PELÍCULA");
        btnConsultarPeli.setToolTipText("");
        btnConsultarPeli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultarPeli.setMargin(new java.awt.Insets(8, 14, 8, 14));
        btnConsultarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPeliActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnActualizar.setText("ACTUALIZAR PELÍCULA");
        btnActualizar.setToolTipText("");
        btnActualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizar.setMargin(new java.awt.Insets(8, 14, 8, 14));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Resumen");
        jLabel5.setToolTipText("");

        peliculaTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        peliculaTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        peliculaTitulo.setToolTipText("");
        peliculaTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliculaTituloActionPerformed(evt);
            }
        });

        peliculaDirector.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        peliculaDirector.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        peliculaDirector.setToolTipText("");
        peliculaDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliculaDirectorActionPerformed(evt);
            }
        });

        pelliculaAn.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        pelliculaAn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pelliculaAn.setToolTipText("");
        pelliculaAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelliculaAnActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Año");
        jLabel3.setToolTipText("");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Director");
        jLabel4.setToolTipText("");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Titulo");
        jLabel2.setToolTipText("");

        peliculaId.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        peliculaId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        peliculaId.setToolTipText("");
        peliculaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliculaIdActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id Pelicula");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(peliculaId, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCrearPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnConsultarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnEliminarpeli, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(peliculaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(peliculaDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(pelliculaAn)))))
                    .addComponent(lbNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peliculaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peliculaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peliculaDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pelliculaAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarpeli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 730, 340));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REDFLIX33");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPeliActionPerformed
        // TODO add your handling code here:
        lbNotificaciones.setText("Se insertó la película " + peliculaTitulo.getText());
        crear();

    }//GEN-LAST:event_btnCrearPeliActionPerformed

    private void btnConsultarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPeliActionPerformed
        // TODO add your handling code here:
        if (!peliculaId.getText().equals("")) {
            buscarPorId();
            //peliculaId.setEnabled(true);
        } else {
            lbNotificaciones.setText("No ha digitado ningun id");
        }
    }//GEN-LAST:event_btnConsultarPeliActionPerformed

    private void peliculaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliculaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peliculaIdActionPerformed

    private void pelliculaAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelliculaAnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelliculaAnActionPerformed

    private void peliculaDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliculaDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peliculaDirectorActionPerformed

    private void peliculaTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliculaTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peliculaTituloActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        //actualizar();
        actualizar();

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarpeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarpeliActionPerformed
        // TODO add your handling code here:
        eliminar();
        limpiarCamposParaCreacion();
    }//GEN-LAST:event_btnEliminarpeliActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpiarCamposParaCreacion();
        lbNotificaciones.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultarPeli;
    private javax.swing.JButton btnCrearPeli;
    private javax.swing.JButton btnEliminarpeli;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNotificaciones;
    private javax.swing.JTextField peliculaDirector;
    private javax.swing.JTextField peliculaId;
    private javax.swing.JTextArea peliculaResumen;
    private javax.swing.JTextField peliculaTitulo;
    private javax.swing.JTextField pelliculaAn;
    // End of variables declaration//GEN-END:variables

    private void buscarPorId() {

        int id = Integer.parseInt(peliculaId.getText());
        Optional<peliculas> optionalpeliculas = repo.findById(id);
        if (optionalpeliculas.isPresent()) {
            peliculas peliculas = optionalpeliculas.get();
            peliculaTitulo.setText(peliculas.getPeliTitulo());
            peliculaDirector.setText(peliculas.getPeliDirector());
            pelliculaAn.setText(String.valueOf(peliculas.getPeliAnio()));
            peliculaResumen.setText(peliculas.getPeliResumen());

            lbNotificaciones.setText(
                    "La pelicula : " + peliculaId.getText() + " -> " + peliculaTitulo.getText()
                    + " se encuentra en el catálogo de Redflix33");
        } else {
            limpiarCamposParaCreacion();
            // Error cuando no existe el id
            lbNotificaciones.setText(
                    "No existe registro en nuestro catálogo de la pelicula con id: " + peliculaId.getText());

        }
    }

    public void limpiarCamposParaCreacion() {
        // peliculaId.setEnabled(false);
        // btnCrearPeli.setEnabled(false);
        peliculaId.setText("");
        peliculaDirector.setText("");
        pelliculaAn.setText("");
        peliculaResumen.setText("");
        peliculaTitulo.setText("");
    }

    private peliculas obtenerDatosDeFormulario() {
        peliculas peliculas = new peliculas();
        peliculas.setPeliTitulo(peliculaTitulo.getText());
        peliculas.setPeliDirector(peliculaDirector.getText());
        peliculas.setPeliAnio(Integer.parseInt(pelliculaAn.getText()));
        peliculas.setPeliResumen(peliculaResumen.getText());
        return peliculas;
    }

    private void crear() {
        peliculas pelicula = obtenerDatosDeFormulario();

        try {
            repo.save(pelicula);
            lbNotificaciones.setText("Se ingresó " + '"' + peliculaTitulo.getText() + '"' + " a nuestro catálogo de películas Redflix33");
        } catch (Exception e) {
            lbNotificaciones.setText("No fue posible ingresar la pelicula" + '"' + peliculaTitulo.getText() + '"' + " al catálogo de películas");
        }
        limpiarCamposParaCreacion();
    }

    private void actualizar() {
        int id = Integer.parseInt(peliculaId.getText());
        try {
            peliculas peliculaDB = repo.findById(id).get();
            peliculas pelicula = obtenerDatosDeFormulario();
            peliculaDB.setPeliDirector(pelicula.getPeliDirector());
            peliculaDB.setPeliTitulo(pelicula.getPeliTitulo());
            peliculaDB.setPeliAnio(pelicula.getPeliAnio());
            peliculaDB.setPeliResumen(pelicula.getPeliResumen());

            repo.save(peliculaDB);
            lbNotificaciones.setText("Se actualizó la pelicula " + peliculaTitulo.getText());
        } catch (Exception e) {
            lbNotificaciones.setText("No es posible actualizar la película " + peliculaTitulo.getText() + " \nPor error: " + e);
        }
    }

    public void eliminar() {
        int id = Integer.parseInt(peliculaId.getText());

        try {
            repo.deleteById(id);
            lbNotificaciones.setText("Se eliminó la película " + id +" -> "+ peliculaTitulo.getText() );
        } catch (Exception e) {
            lbNotificaciones.setText("Ocurrio un error al eliminar. Error presentado: " + e);
        }

    }

}
